; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_pressure_burst=music_data_pressure_burst
.endif

music_data_pressure_burst:
	.byte 1
	.word @instruments
	.word @instruments_exp
	.word @samples-4
; 00 : Pressure Burst
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.word @song0ch8
	.word @song0ch9
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_pressure_burst
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env46,@env42,@env33,@env0 ; 00 : kick attack(E3)
	.word @env30,@env39,@env33,@env0 ; 01 : OH(F#3)
	.word @env40,@env39,@env33,@env0 ; 02 : HH(F#3)
	.word @env6,@env51,@env33,@env0 ; 03 : noise step(D#3)
	.word @env43,@env7,@env33,@env0 ; 04 : crash(F#3)
	.word @env26,@env54,@env33,@env0 ; 05 : clap(B2)
	.word @env25,@env32,@env33,@env0 ; 06 : SS Noise snare(D3)
	.word @env18,@env39,@env33,@env0 ; 07 : OH 1/ 2(F#3)
	.word @env17,@env28,@env38,@env0 ; 08 : Duty 1
	.word @env13,@env28,@env55,@env0 ; 09 : Lead 50 50 25
	.word @env17,@env28,@env33,@env0 ; 0a : Duty 0
	.word @env10,@env28,@env35,@env0 ; 0b : ARP
	.word @env13,@env28,@env36,@env0 ; 0c : Lead 25 25 12.5
	.word @env17,@env56,@env33,@env0 ; 0d : Tribass sub
	.word @env10,@env28,@env55,@env0 ; 0e : Lead 50 50 25(echo)

@instruments_exp:
	.word @env29, @env28, @env0 ; 00 : PWM coustom
	.word @env9
	.byte $40, $20
	.word @n163_inst0_waves
	.byte $00, $00, $00, $00
	.word @env53, @env56, @env0 ; 01 : N163 rhythm guitar&bass
	.word @env0
	.byte $80, $20
	.word @n163_inst1_waves
	.byte $00, $00, $00, $00
	.word @env44, @env28, @env0 ; 02 : N163 arp
	.word @env0
	.byte $60, $20
	.word @n163_inst2_waves
	.byte $00, $00, $00, $00
	.word @env50, @env56, @env0 ; 03 : N163 loud riff bass
	.word @env0
	.byte $80, $20
	.word @n163_inst3_waves
	.byte $00, $00, $00, $00

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$00,$00,$00,$80,$a9,$cb,$ed,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env2:
	.byte $00,$00,$00,$00,$00,$00,$ba,$dc,$fe,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env3:
	.byte $00,$00,$00,$00,$00,$a0,$cb,$ed,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env4:
	.byte $00,$00,$00,$00,$00,$00,$b0,$dc,$fe,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env5:
	.byte $00,$00,$00,$00,$00,$00,$c0,$ed,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env6:
	.byte $00,$c7,$c3,$c3,$c6,$c5,$c5,$c4,$03,$c3,$03,$c2,$00,$0b
@env7:
	.byte $c0,$c0,$c2,$00,$02
@env8:
	.byte $00,$c0,$be,$bd,$bd,$be,$bf,$c1,$c2,$c3,$c3,$c2,$00,$01
@env9:
	.byte $00,$c0,$c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$cb,$cc,$cd,$ce,$cd,$cc,$cb,$ca,$c9,$cf,$d0,$d1,$d2,$d3,$c3,$c2,$c1,$00,$01
@env10:
	.byte $05,$c7,$c5,$00,$02,$c1,$00,$05
@env11:
	.byte $00,$00,$40,$65,$87,$a9,$cb,$ed,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env12:
	.byte $b8,$fd,$ff,$ef,$bc,$aa,$9a,$88,$77,$66,$55,$44,$13,$00,$00,$42
@env13:
	.byte $06,$cd,$ca,$c9,$00,$03,$c1,$00,$06
@env14:
	.byte $00,$00,$00,$00,$70,$98,$ba,$dc,$fe,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env15:
	.byte $00,$c0,$bf,$03,$c0,$c0,$c1,$02,$c1,$00,$01
@env16:
	.byte $00,$00,$43,$65,$87,$a9,$cb,$ed,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env17:
	.byte $00,$cf,$7f,$00,$02
@env18:
	.byte $00,$c7,$03,$c6,$c5,$c4,$03,$c2,$00,$07
@env19:
	.byte $00,$21,$43,$65,$87,$a9,$cb,$ed,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env20:
	.byte $00,$00,$00,$00,$00,$00,$00,$ed,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env21:
	.byte $00,$00,$00,$00,$00,$a9,$cb,$ed,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env22:
	.byte $00,$00,$00,$00,$00,$98,$ba,$dc,$fe,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env23:
	.byte $00,$00,$00,$65,$87,$a9,$cb,$ed,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env24:
	.byte $00,$00,$00,$60,$87,$a9,$cb,$ed,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env25:
	.byte $00,$c7,$c4,$04,$c3,$04,$c2,$04,$c1,$00,$08
@env26:
	.byte $00,$cd,$c3,$cb,$c8,$c6,$c5,$c4,$c4,$c3,$c2,$c1,$00,$0b
@env27:
	.byte $00,$00,$00,$00,$87,$a9,$cb,$ed,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env28:
	.byte $c0,$7f,$00,$01
@env29:
	.byte $04,$c6,$00,$01,$c1,$00,$04
@env30:
	.byte $00,$c9,$03,$c7,$c0,$00,$04
@env31:
	.byte $00,$00,$00,$00,$00,$00,$00,$e0,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env32:
	.byte $c0,$c1,$c2,$00,$02
@env33:
	.byte $7f,$00,$00
@env34:
	.byte $00,$c0,$bc,$ba,$bc,$c0,$c4,$c6,$c4,$00,$01
@env35:
	.byte $c2,$7f,$00,$00
@env36:
	.byte $c1,$c1,$c0,$00,$02
@env37:
	.byte $00,$00,$00,$00,$00,$00,$00,$00,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env38:
	.byte $c1,$7f,$00,$00
@env39:
	.byte $c0,$c2,$00,$01
@env40:
	.byte $00,$c3,$c3,$c2,$c1,$c0,$00,$05
@env41:
	.byte $00,$c0,$bf,$be,$02,$bf,$c1,$c2,$02,$c1,$00,$01
@env42:
	.byte $c0,$c4,$00,$01
@env43:
	.byte $00,$ca,$02,$c9,$03,$c8,$03,$c7,$03,$c6,$03,$c5,$03,$c4,$03,$c3,$03,$c2,$03,$c1,$00,$13
@env44:
	.byte $00,$c8,$7f,$00,$02
@env45:
	.byte $c0,$cc,$00,$00
@env46:
	.byte $00,$c5,$c3,$c2,$c1,$c0,$00,$05
@env47:
	.byte $00,$00,$00,$00,$00,$90,$ba,$dc,$fe,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env48:
	.byte $ff,$ff,$ff,$00,$00,$00,$ff,$00,$ff,$ff,$00,$00,$ff,$00,$ff,$00
@env49:
	.byte $00,$20,$43,$65,$87,$a9,$cb,$ed,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env50:
	.byte $05,$cc,$ca,$00,$02,$c1,$00,$05
@env51:
	.byte $c0,$b8,$c4,$c1,$c2,$00,$04
@env52:
	.byte $00,$00,$00,$00,$00,$00,$cb,$ed,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
@env53:
	.byte $05,$ca,$c8,$00,$02,$c1,$00,$05
@env54:
	.byte $c0,$bf,$c1,$c0,$00,$03
@env55:
	.byte $c2,$c2,$c1,$00,$02
@env56:
	.byte $cc,$c0,$00,$01

@n163_inst0_waves:
	.word @env37
	.word @env31
	.word @env20
	.word @env5
	.word @env4
	.word @env2
	.word @env47
	.word @env22
	.word @env14
	.word @env24
	.word @env23
	.word @env11
	.word @env16
	.word @env49
	.word @env19
	.word @env27
	.word @env1
	.word @env21
	.word @env3
	.word @env52

@n163_inst1_waves:
	.word @env48

@n163_inst2_waves:
	.word @env12

@n163_inst3_waves:
	.word @env48

@samples:
	.byte $07+.lobyte(FAMISTUDIO_DPCM_PTR),$1d,$0f,$40 ; 00 Clap (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$1b,$0f,$40 ; 01 Punch Kick (Pitch:15)
	.byte $0f+.lobyte(FAMISTUDIO_DPCM_PTR),$34,$0f,$40 ; 02 RECCA SHOUT (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $ff, $bf
@song0ref3:
	.byte $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $ff
	.byte $41, $0d
	.word @song0ref3
	.byte $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $df, $71, $51
	.byte $05, $f0, $49, .lobyte(@env34), .hibyte(@env34), $92, $24, $dd, $48, $49, .lobyte(@env0), .hibyte(@env0), $4a, $92
	.byte $23, $81, $43, $24, $8f, $45, $27, $87, $45, $29, $87, $45, $2c, $87, $45, $24, $87, $45, $27, $87, $45, $29, $87, $45
	.byte $00, $89, $1d, $87, $45, $20, $87, $45, $24
@song0ref100:
	.byte $87, $45, $27, $87, $45, $29, $87, $45, $27, $87, $45, $24, $87, $45, $48, $26, $87, $45, $1d, $87, $45, $20, $87, $45
	.byte $26, $87, $45, $25, $87, $45, $20, $87, $45, $25, $87, $45, $24, $93, $45, $22, $87, $45, $20, $87, $45, $24, $87, $45
	.byte $27, $89, $43, $50, $40, $33, $27, $89, $28, $93, $45, $48, $29, $87, $45, $76, $29, $87, $45, $7f, $50, $32, $35, $2a
	.byte $89, $76, $43, $50, $32, $35, $2a, $89, $7f, $29, $87, $45, $76, $29, $87, $45, $7f, $50, $32, $35, $2a, $89, $76, $43
	.byte $50, $32, $35, $2a, $89, $7f, $29, $87, $45, $1d, $87, $45, $20, $87, $45, $24, $87, $45, $22, $87, $45, $24, $87, $45
	.byte $20, $87, $45, $22, $89, $48, $49, .lobyte(@env34), .hibyte(@env34), $97, $43, $50, $55, $2e, $22, $89, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $00, $89, $78, $92, $22, $87, $45, $24, $87, $45, $20, $87, $45, $22, $89, $49, .lobyte(@env34)
	.byte .hibyte(@env34), $97, $43, $50, $55, $2e, $22, $89, $49, .lobyte(@env0), .hibyte(@env0), $4a, $00, $89, $7f, $92, $24
	.byte $87, $45, $27, $87, $45, $29, $87, $45, $2b, $87, $45, $48, $2c, $93, $45, $1d, $87, $45, $2b, $93, $45, $1d, $87, $45
	.byte $29, $93, $45, $1d, $87, $45, $24, $93, $45, $20
	.byte $41, $0e
	.word @song0ref100
	.byte $48, $25, $85, $43, $26, $8b, $45, $1d, $87, $45, $22, $93, $45, $1d, $87, $45, $25, $93, $45, $1d, $87, $45, $24, $93
	.byte $45, $1d, $87, $45, $22, $87, $45, $20, $87, $45, $1b, $87, $45, $1c, $87, $45, $48, $1d, $95, $43, $50, $13, $29, $24
	.byte $95, $7a, $1d, $95, $43, $50, $13, $29, $24, $95, $78, $1d, $95, $43, $50, $13, $29, $24, $95, $76, $1d, $95, $43, $50
	.byte $13, $29, $24, $95, $48, $7f, $00, $f5, $98, $16, $85, $43, $18, $8b, $45, $1d, $87, $45, $20, $87, $45, $27, $87, $45
	.byte $50, $fe, $2e, $30, $89, $48, $af, $43, $24, $89, $43, $50, $4c, $30, $24, $89, $27, $85, $43, $29, $81, $49, .lobyte(@env8)
	.byte .hibyte(@env8), $95, $45, $49, .lobyte(@env0), .hibyte(@env0), $4a, $98, $24, $87, $45, $22, $87, $45, $20, $87, $45
	.byte $1d, $87, $45, $24, $87, $45, $22, $87, $45, $20, $87, $45, $48, $27, $93, $45, $24, $87, $45, $29, $93, $45, $24, $87
	.byte $45, $20, $85, $43, $22, $81, $49, .lobyte(@env8), .hibyte(@env8), $95, $45, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $98, $1a, $87, $45, $20, $93, $45, $1a, $87, $45, $22, $93, $45, $1a, $87, $45, $48, $1d, $85, $43, $1f, $8d, $49, .lobyte(@env8)
	.byte .hibyte(@env8), $a1, $45, $49, .lobyte(@env0), .hibyte(@env0), $4a, $98, $20, $89, $43, $1f, $89, $20, $89, $43, $1f
	.byte $89, $20, $89, $43, $1f, $89, $20, $87, $45, $1a, $85, $43, $1b, $8b, $45, $18, $87, $45, $1d, $89, $48, $97, $43, $50
	.byte $13, $29, $24, $95, $78, $1d, $a1, $43, $50, $13, $29, $24, $95, $76, $1d, $89, $7f, $24, $93, $45, $28, $85, $43, $29
	.byte $8b, $45, $2b, $93, $45, $48
@song0ref581:
	.byte $2c, $93, $45, $2e, $93, $45, $30, $87, $45, $00, $89, $49, .lobyte(@env8), .hibyte(@env8), $2e, $95, $43, $50, $2b
	.byte $3a, $2e, $89, $49, .lobyte(@env0), .hibyte(@env0), $4a, $00, $89, $98, $2b, $93, $45, $27, $87, $45, $00, $89, $27
	.byte $85, $43, $29, $81, $49, .lobyte(@env8), .hibyte(@env8), $8b, $48, $95
@song0ref629:
	.byte $45, $49, .lobyte(@env0), .hibyte(@env0), $4a, $98, $2b, $93, $45, $2c, $87, $45, $00, $89, $26, $85, $43, $27, $81
	.byte $49, .lobyte(@env8), .hibyte(@env8), $a1, $45, $49, .lobyte(@env0), .hibyte(@env0), $4a, $98, $24, $93, $45, $20, $93
	.byte $45, $22, $89, $49, .lobyte(@env8), .hibyte(@env8), $8b, $48, $95
@song0ref672:
	.byte $45, $49, .lobyte(@env0), .hibyte(@env0), $4a, $98, $25, $93, $45, $29, $93, $45, $2e, $93, $45, $31, $93, $45, $30
	.byte $93, $45, $2e, $87, $45, $00, $89, $29, $85, $43, $2b, $8d, $48
@song0ref704:
	.byte $43, $50, $33, $37, $2b, $89, $00, $89, $24, $93, $45, $29, $87, $45, $00, $89, $49, .lobyte(@env8), .hibyte(@env8)
	.byte $27, $85, $43, $28, $bd, $43, $50, $3c, $34, $28, $89, $49, .lobyte(@env0), .hibyte(@env0), $4a, $92, $24, $87, $45
	.byte $27, $87, $45, $29
@song0ref746:
	.byte $87, $45, $48, $2b, $85, $43, $2c, $8b
@song0ref754:
	.byte $45, $24, $87, $45, $00, $89, $27, $89, $43, $29, $87, $45, $00, $89, $29, $87, $45, $00, $89, $29, $87, $45, $24, $87
	.byte $45, $29, $87, $45, $00, $89, $24, $87, $45, $29, $87, $45, $2b, $87, $45, $48, $2c, $93
	.byte $41, $0d
	.word @song0ref754
@song0ref799:
	.byte $30, $87, $45, $00, $89, $30, $87, $45, $2e, $87, $45, $00, $89, $2c, $87, $45, $2b, $87, $45, $27, $87, $45, $22, $87
	.byte $45, $48, $24, $87, $45, $00, $89, $1d, $89, $45, $00, $87, $20, $89, $43, $22, $89, $45, $00, $87, $27, $89, $45, $00
	.byte $87, $29, $89, $45, $00, $87, $2b, $93, $45, $2c, $87, $45, $2e, $85, $43, $30, $8b, $45, $48, $2e, $87, $45, $00, $89
	.byte $2c, $93, $45, $2b, $87, $45, $29, $87, $45, $00, $87, $49, .lobyte(@env8), .hibyte(@env8), $81, $92, $2b, $93, $45
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $27, $87, $45, $2c, $85, $43, $2e, $8b, $45, $2b, $87, $45, $27, $87, $45
	.byte $24, $87, $45, $27
	.byte $41, $2e
	.word @song0ref746
	.byte $41, $0d
	.word @song0ref754
	.byte $41, $19
	.word @song0ref799
	.byte $48, $20, $89, $45, $00, $87, $24, $89, $45, $00, $87, $27, $89, $43, $29, $89, $45, $00, $87, $2c, $87, $45, $29, $87
	.byte $45, $2c, $87, $45, $30, $87, $45, $2e, $87, $45, $2c, $87, $45, $29, $87, $45, $27, $85, $43, $29, $8d, $48, $95, $45
	.byte $2b, $93, $45, $2c, $87, $45, $00, $89, $29, $85, $43, $2b, $81, $49, .lobyte(@env8), .hibyte(@env8), $97, $43, $50
	.byte $33, $37, $2b, $89, $49, .lobyte(@env0), .hibyte(@env0), $4a, $92, $24, $93, $45, $2e, $93, $45, $2b, $93, $45, $48
@song0ref1008:
	.byte $30, $93, $45, $29, $93, $45, $24, $87, $45, $00, $89, $2b, $85, $43, $2c, $81, $49, .lobyte(@env8), .hibyte(@env8)
	.byte $97, $43, $50, $30, $38, $2c, $89, $49, .lobyte(@env0), .hibyte(@env0), $4a, $92
@song0ref1039:
	.byte $2d, $81, $43, $2e, $8f, $45, $2c, $87, $45, $00, $89, $29, $85, $43, $2b, $81, $49, .lobyte(@env8), .hibyte(@env8)
	.byte $8b, $48, $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $43, $2c, $89, $43, $2b, $87, $45, $92
@song0ref1073:
	.byte $27, $87, $45, $00, $89, $27, $85, $43, $29, $81, $49, .lobyte(@env8), .hibyte(@env8), $97, $43, $50, $39, $35, $29
	.byte $89, $49, .lobyte(@env0), .hibyte(@env0), $4a, $92, $24, $93, $45, $27, $93, $45, $29, $93, $45, $48
@song0ref1108:
	.byte $00, $95, $30, $93, $45, $29, $87, $45, $00, $89, $2c, $85, $43, $2e, $81, $49, .lobyte(@env8), .hibyte(@env8), $97
	.byte $43, $50, $2b, $3a, $2e, $89, $49, .lobyte(@env0), .hibyte(@env0), $4a, $92, $2c, $93, $45, $2b, $87, $45, $00, $89
	.byte $29, $95, $48, $43, $50, $19, $35, $2a, $95, $7a, $29, $95, $43, $50, $19, $35, $2a, $95, $78, $29, $95, $43, $50, $19
	.byte $35, $2a, $95, $74, $29, $95, $43, $50, $19, $35, $2a, $95, $72, $29, $95, $48, $43, $50, $19, $35, $2a, $95, $70, $00
	.byte $ff, $a5
	.byte $41, $0d
	.word @song0ref3
	.byte $bf, $42
	.word @song0ch0loop
@song0ch1:
@song0ref1203:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $ff
	.byte $41, $0f
	.word @song0ref1203
	.byte $bf, $ff, $bf, $ff, $bf
@song0ch1loop:
	.byte $4c
@song0ref1229:
	.byte $7f, $96
@song0ref1231:
	.byte $1f, $87, $45, $76, $2b
@song0ref1236:
	.byte $87, $45, $7f, $20, $87, $45, $22, $87, $45, $76, $20, $87, $45, $22, $87, $45, $7f, $1f, $87, $45, $76, $22
	.byte $41, $0e
	.word @song0ref1236
@song0ref1261:
	.byte $7f, $29, $87, $45, $27, $87, $45, $24, $87, $45, $27, $87, $45, $1f, $87, $45, $76, $27
	.byte $41, $12
	.word @song0ref1236
	.byte $41, $0e
	.word @song0ref1236
	.byte $41, $10
	.word @song0ref1261
	.byte $41, $12
	.word @song0ref1236
	.byte $41, $0e
	.word @song0ref1236
	.byte $41, $0c
	.word @song0ref1261
	.byte $20, $87, $45, $76, $27
@song0ref1302:
	.byte $87, $45, $7f, $22, $87, $45, $76, $20, $87, $45, $7f, $24, $87, $45, $76, $22, $87, $45, $7f, $27, $87, $45, $76, $24
	.byte $87, $45, $7f, $29, $87, $45, $76, $27, $87, $45, $7f, $2c, $87, $45, $76, $29, $87, $45, $7f, $30, $87, $45, $76, $2c
	.byte $87, $45, $7f, $35, $87, $45, $76, $30, $87, $45, $00, $ff, $bd
	.byte $41, $0e
	.word @song0ref1203
@song0ref1366:
	.byte $7f, $1d, $85, $76, $43, $29, $81, $7f, $20, $85, $76, $43, $1d, $81, $7f, $24, $85, $76, $43, $20, $81, $7f, $29, $85
	.byte $76, $43, $24, $81, $7f, $24, $85, $76, $43, $29, $81, $7f, $29, $85, $76, $43, $24, $81, $7f, $24, $85, $76, $43, $29
	.byte $81, $7f, $20, $85, $76, $43, $24, $81
	.byte $41, $20
	.word @song0ref1366
	.byte $41, $20
	.word @song0ref1366
	.byte $41, $20
	.word @song0ref1366
	.byte $41, $20
	.word @song0ref1366
	.byte $41, $20
	.word @song0ref1366
	.byte $7f, $20, $87, $45, $76, $2c
	.byte $41, $26
	.word @song0ref1302
	.byte $7f, $29, $87, $45, $76, $30, $87, $45, $00, $95, $98
	.byte $41, $1d
	.word @song0ref581
	.byte $49, .lobyte(@env8), .hibyte(@env8), $a1
	.byte $41, $17
	.word @song0ref629
	.byte $49, .lobyte(@env8), .hibyte(@env8), $a1
	.byte $41, $19
	.word @song0ref672
	.byte $41, $12
	.word @song0ref704
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $00, $89
	.byte $41, $16
	.word @song0ref1229
	.byte $41, $0e
	.word @song0ref1236
	.byte $41, $0c
	.word @song0ref1261
@song0ref1492:
	.byte $20, $87, $45, $76, $27, $87, $45, $7f, $24, $87, $45, $27, $87, $45, $76, $24, $87, $45, $27, $87, $45, $7f
	.byte $41, $12
	.word @song0ref1492
@song0ref1517:
	.byte $7f, $20, $87, $45, $22, $87, $45, $24, $87, $45, $27, $87, $45, $20, $87, $45, $76, $27
@song0ref1535:
	.byte $87, $45, $7f, $24, $87, $45, $25, $87, $45, $76, $24, $87, $45, $25, $87, $45, $7f, $20, $87, $45, $76, $25
	.byte $41, $11
	.word @song0ref1535
	.byte $24, $87, $45, $25, $87, $45, $29, $87, $45, $22, $87, $45, $76, $29
@song0ref1574:
	.byte $87, $45, $7f, $25, $87, $45, $27, $87, $45, $76, $25, $87, $45, $27, $87, $45, $7f, $22, $87, $45, $76, $27
	.byte $41, $11
	.word @song0ref1574
	.byte $25, $87, $45, $27, $87, $45, $2b, $87, $45
	.byte $41, $16
	.word @song0ref1231
	.byte $41, $0e
	.word @song0ref1236
	.byte $41, $0c
	.word @song0ref1261
	.byte $41, $12
	.word @song0ref1492
	.byte $7f
	.byte $41, $12
	.word @song0ref1492
	.byte $41, $22
	.word @song0ref1517
	.byte $41, $11
	.word @song0ref1535
	.byte $24, $87, $45, $7a, $4b, .lobyte(@env45), .hibyte(@env45), $92, $24, $95, $95, $45, $4d, $24, $93, $45, $4d, $29, $87
	.byte $45, $72, $4d, $24, $87, $45, $7a, $4d, $28, $ab, $45, $4d, $20, $87, $45, $72, $4d, $28, $87, $45, $7a, $4d, $2b, $87
	.byte $45, $72, $4d, $20, $87, $45, $7a, $4d, $28, $87, $45, $72, $4d, $2b, $87, $45, $7f, $00, $95, $4b, .lobyte(@env28)
	.byte .hibyte(@env28), $4c, $9c
	.byte $41, $12
	.word @song0ref1008
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $9c
	.byte $41, $0e
	.word @song0ref1039
	.byte $49, .lobyte(@env8), .hibyte(@env8), $a3, $49, .lobyte(@env0), .hibyte(@env0), $4a, $43, $2c, $89, $43, $2b, $87, $45
	.byte $9c
	.byte $41, $0c
	.word @song0ref1073
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $9c, $24, $93, $45, $27, $93, $45, $29, $93, $45
	.byte $41, $11
	.word @song0ref1108
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $9c, $2c, $93, $45, $24, $95, $43, $50, $22, $30, $25, $95, $7a, $24, $95
	.byte $43, $50, $22, $30, $25, $95, $78, $24, $95, $43, $50, $22, $30, $25, $95, $74, $24, $95, $43, $50, $22, $30, $25, $95
	.byte $72, $24, $95, $43, $50, $22, $30, $25, $95, $70, $00, $ff, $a5
	.byte $41, $0e
	.word @song0ref1203
	.byte $42
	.word @song0ch1loop
@song0ch2:
	.byte $41, $10
	.word @song0ref1203
	.byte $ff, $bf, $ff, $bf, $9a
@song0ref1814:
	.byte $0f, $8f, $00, $83, $11, $8f, $00, $9b, $0c, $8f, $00, $83, $0f, $8f, $00, $8f, $11, $83, $00, $8f, $11, $83, $00, $83
	.byte $0c, $83, $00, $83, $0d, $83, $00, $83, $0e, $8f, $00, $83, $0c, $8f, $00, $83, $0e, $8f, $00, $83, $05
@song0ref1859:
	.byte $a7, $00, $83, $11, $8f, $00, $83, $0c, $8f, $00, $83, $0e, $8f, $00, $83
	.byte $41, $29
	.word @song0ref1814
@song0ref1877:
	.byte $83, $00, $8f, $08, $85, $43, $0a, $87, $00, $83, $05, $a7, $00, $83, $04, $ad
	.byte $41, $3c
	.word @song0ref1814
	.byte $41, $29
	.word @song0ref1814
	.byte $41, $0f
	.word @song0ref1877
@song0ch2loop:
@song0ref1903:
	.byte $05, $9b, $00, $83, $05, $83, $00, $83, $11, $8f, $00, $83, $08, $83, $00, $83, $0a, $83, $00, $83
	.byte $41, $0c
	.word @song0ref1903
	.byte $05, $8f, $00, $83
	.byte $41, $0c
	.word @song0ref1903
	.byte $11, $8f, $00, $83, $0f, $89, $43, $11, $83, $00, $83, $0f, $8f, $00, $83, $0c, $8f, $00, $83, $08, $8f, $00, $83
	.byte $41, $14
	.word @song0ref1903
	.byte $41, $0c
	.word @song0ref1903
	.byte $0a, $83, $00, $83, $0c, $83, $00, $83
	.byte $41, $0c
	.word @song0ref1903
	.byte $0f, $83, $00, $83, $0c, $83, $00, $8f, $0f, $83, $00, $83, $10, $83, $00, $8f, $11, $95, $43, $50, $43, $1d, $15, $95
	.byte $41, $2c
	.word @song0ref1814
	.byte $0a
	.byte $41, $0f
	.word @song0ref1859
	.byte $41, $2c
	.word @song0ref1814
@song0ref2007:
	.byte $16, $a7, $00, $83, $14, $8f, $00, $83, $13, $8f, $00, $83, $0c, $83, $00, $83, $0e, $83, $00, $83
	.byte $41, $2c
	.word @song0ref1814
	.byte $41, $14
	.word @song0ref2007
	.byte $41, $0f
	.word @song0ref1814
	.byte $83, $11, $83, $00, $83, $16, $8f
@song0ref2043:
	.byte $00, $83, $14, $83, $00, $83, $11, $83, $00, $83, $0f, $83, $00, $83, $05, $8f, $00, $83, $11, $83, $00, $83, $08, $8f
	.byte $00, $83, $11, $83, $00, $83, $0a, $8f, $00, $83, $11, $83, $00, $83, $0c, $83, $00, $83, $17, $8f, $00, $83, $16, $83
	.byte $41, $0e
	.word @song0ref2043
	.byte $41, $2c
	.word @song0ref1814
	.byte $0a
	.byte $41, $0f
	.word @song0ref1859
	.byte $41, $2c
	.word @song0ref1814
	.byte $41, $14
	.word @song0ref2007
@song0ref2107:
	.byte $0d, $8f, $00, $83, $08, $8f, $00, $83, $0d, $8f, $00, $83, $0c, $8f, $00, $9b, $08, $8f, $00, $83, $05, $8f, $00, $83
	.byte $0a, $95, $91, $00, $83, $0c, $8f, $00, $83, $0d, $8f, $00, $83, $08, $a7, $00, $83, $14, $8f, $00, $83, $0f, $8f, $00
	.byte $83, $08, $8f, $00, $83, $06, $8f, $00, $83, $0a, $8f, $00, $83, $0d, $8f, $00, $83, $12, $a7, $00, $83, $0d, $8f, $00
	.byte $83, $0a, $8f, $00, $83, $0c, $95, $85, $00, $83, $0c, $83, $00, $83, $0c, $9b, $00, $83, $0c, $83, $00, $83, $0c, $9b
	.byte $00, $83, $0c, $83, $00, $83, $18, $8f, $00, $83, $16, $83
	.byte $41, $13
	.word @song0ref2043
@song0ref2218:
	.byte $8f, $00, $83, $05, $8f, $00, $83, $11, $8f, $00, $83, $05, $8f, $00, $83, $11, $8f, $00, $83, $05, $8f, $00, $83, $11
@song0ref2242:
	.byte $8f, $00, $83, $08, $8f, $00, $83, $14, $8f, $00, $83, $08, $8f, $00, $83, $14
	.byte $41, $10
	.word @song0ref2242
@song0ref2261:
	.byte $8f, $00, $83, $01, $8f, $00, $83, $0d, $8f, $00, $83, $01, $8f, $00, $83, $0d
	.byte $41, $10
	.word @song0ref2261
	.byte $8f, $00, $83, $03, $8f, $00, $83, $0f, $8f, $00, $83, $03, $8f, $00, $83, $0f, $8f, $00, $83, $03, $8f, $00, $83, $18
	.byte $8f, $00, $83, $16, $83
	.byte $41, $13
	.word @song0ref2043
	.byte $41, $28
	.word @song0ref2218
	.byte $41, $10
	.word @song0ref2242
	.byte $41, $10
	.word @song0ref2261
	.byte $41, $0f
	.word @song0ref2261
	.byte $0a, $95, $91, $00, $83, $0c, $8f, $00, $83, $0d, $83, $00, $8f, $0a, $85, $43, $0c, $93, $00, $8f, $16, $8f, $00, $83
	.byte $13, $83, $00, $83, $10, $83, $00, $83, $0c, $83, $00, $83, $0f, $83, $00, $83, $0a, $8f, $00, $83, $01, $8f, $00, $83
	.byte $05, $8f, $00, $83, $0d, $a7, $00, $83, $05, $8f, $00, $83, $0d, $8f, $00, $83, $0c, $95, $8f, $00, $83, $13, $91, $00
	.byte $83, $0f, $8f, $00, $83, $11, $a7, $00, $83, $05, $8f, $00, $83, $0c, $8f, $00, $83, $0f, $8f, $00, $83
	.byte $41, $0c
	.word @song0ref2107
	.byte $0f, $a7, $00, $83, $13, $8f, $00, $83, $0f, $8f, $00, $83, $05, $95, $91, $00, $cb, $05, $d7, $00, $83
	.byte $41, $3c
	.word @song0ref1814
	.byte $41, $29
	.word @song0ref1814
	.byte $41, $0f
	.word @song0ref1877
	.byte $41, $3c
	.word @song0ref1814
	.byte $41, $29
	.word @song0ref1814
	.byte $41, $0f
	.word @song0ref1877
	.byte $42
	.word @song0ch2loop
@song0ch3:
	.byte $41, $10
	.word @song0ref1203
	.byte $74, $94, $23, $ad, $22, $83, $21, $83, $1f, $83, $1e, $83, $1d, $83, $1c, $83, $1b, $83, $1a, $83, $19, $83, $18, $a1
	.byte $17, $83, $18, $83, $19, $83, $1a, $83, $1b, $83, $1c, $83, $1b, $83, $1a, $83, $19, $83, $18, $83, $17, $83, $16, $83
	.byte $15, $83, $16, $83, $17, $83, $18, $83, $19, $95, $1a, $83, $1b, $95, $7f
@song0ref2528:
	.byte $86, $1c, $89, $1c, $89, $1c, $89, $1c, $89, $1b, $89, $1b, $89, $1b, $89, $1b
@song0ref2544:
	.byte $89
@song0ref2545:
	.byte $88
@song0ref2546:
	.byte $1f, $ad
@song0ref2548:
	.byte $86, $1c, $95, $82, $1f, $95, $80, $1d, $89, $00, $89, $82, $1f, $95, $86, $1c, $95, $82, $1f, $95, $80, $1d, $89, $00
	.byte $89, $82, $1f, $95
	.byte $41, $0e
	.word @song0ref2548
	.byte $41, $16
	.word @song0ref2545
	.byte $86, $1c, $95, $82, $1f, $95, $88, $1f, $ad, $1f, $ad
	.byte $41, $16
	.word @song0ref2546
	.byte $41, $0e
	.word @song0ref2548
	.byte $41, $16
	.word @song0ref2545
	.byte $86, $1c, $95, $82, $1f, $95
	.byte $41, $10
	.word @song0ref2528
@song0ch3loop:
@song0ref2612:
	.byte $88, $1f, $ad
@song0ref2615:
	.byte $8c, $1b, $95, $84, $1f, $89, $1f, $89, $8e, $1f, $95, $80, $1d, $89, $00, $89, $8c, $1b, $95, $8e, $1f, $95, $80, $1d
	.byte $89, $00, $89, $8e, $1f, $95
	.byte $41, $0e
	.word @song0ref2615
	.byte $1b, $89, $1b, $89
	.byte $41, $18
	.word @song0ref2612
	.byte $41, $0c
	.word @song0ref2615
	.byte $73, $90, $18, $83, $74, $19, $83, $76, $1a, $83, $77, $1b, $83, $78, $1c, $83, $79, $1d, $83, $7a, $1e, $83, $7b, $1f
	.byte $83
@song0ref2683:
	.byte $78, $94, $1f, $83, $1d, $8f, $1c, $83, $1b, $83, $90, $1a, $83, $18, $83, $7f
@song0ref2699:
	.byte $8a, $18, $95, $84, $1f, $89, $1f, $89, $80, $1d, $89, $00, $89, $84, $1f, $89, $1f, $89
	.byte $41, $0e
	.word @song0ref2699
	.byte $41, $0e
	.word @song0ref2699
	.byte $8a, $18, $95, $84, $1f, $89, $1f, $89, $88, $1f, $ad
	.byte $41, $0e
	.word @song0ref2699
	.byte $41, $0e
	.word @song0ref2699
	.byte $41, $0e
	.word @song0ref2699
	.byte $8a, $18, $89, $18, $89, $00, $89, $18, $89, $88, $1f, $ad
	.byte $41, $0e
	.word @song0ref2699
	.byte $41, $0e
	.word @song0ref2699
	.byte $41, $0e
	.word @song0ref2699
	.byte $8a, $18, $89, $18, $89, $00, $89, $18, $89, $88, $1f, $ad
	.byte $41, $0e
	.word @song0ref2699
	.byte $8a, $18, $95, $84, $1f, $89, $1f, $89, $88, $1f, $a1, $1f, $a1, $1f, $a1, $1f, $95, $80, $1d, $83, $1d, $83, $8a, $18
	.byte $95, $18, $83, $18, $83, $18, $89
	.byte $41, $1a
	.word @song0ref2683
	.byte $41, $0e
	.word @song0ref2699
	.byte $41, $0e
	.word @song0ref2699
	.byte $8a, $18, $95, $84, $1f, $89, $1f, $89, $88, $1f, $ad
	.byte $41, $0e
	.word @song0ref2699
	.byte $41, $0e
	.word @song0ref2699
	.byte $41, $0e
	.word @song0ref2699
	.byte $86, $1c, $89, $1c, $89, $1c, $89, $1c, $89, $80, $1d, $89, $00, $89, $84, $1f, $89, $00, $89, $1f, $89, $00, $89, $80
	.byte $1d, $89, $84, $1f, $89, $8a, $18, $95, $80, $1d, $89, $84, $1f, $83, $1f, $83, $80, $1d, $89, $84, $1f, $89, $80, $1d
	.byte $89, $84, $1f, $83, $1f, $83, $00, $89, $1f, $89, $80, $1d, $89, $00, $89, $84, $1f, $89, $00, $89, $80, $1d, $89, $84
	.byte $1f, $83, $1f, $83, $8a, $18, $95, $80, $1d, $89, $84, $1f, $89, $00, $89, $80, $1d, $89, $84, $1f, $89
@song0ref2932:
	.byte $1f, $89, $80, $1d, $89, $84, $1f, $89, $80, $1d, $89, $84, $1f, $89, $80, $1d, $89, $84
	.byte $41, $0c
	.word @song0ref2932
	.byte $1d, $89, $1d, $89, $1d, $89, $88, $1f, $95, $97, $1f, $ad
@song0ref2965:
	.byte $1f, $ad, $80, $1d, $89, $00, $89, $86, $1c, $89, $1c, $89, $1c, $89, $1c
	.byte $41, $17
	.word @song0ref2544
	.byte $41, $0e
	.word @song0ref2548
	.byte $41, $16
	.word @song0ref2545
	.byte $86, $1c, $95, $82, $1f, $95, $80, $1d, $89, $00, $89, $1d, $89, $00, $89, $86, $1c, $89, $1c, $89, $1c, $89, $1c
	.byte $41, $17
	.word @song0ref2544
	.byte $41, $0e
	.word @song0ref2548
	.byte $41, $0e
	.word @song0ref2545
	.byte $88, $1f, $95, $97, $80, $1d, $89, $00, $89, $86, $1c, $95, $88
	.byte $41, $0d
	.word @song0ref2965
@song0ref3037:
	.byte $89, $88, $1f, $ad, $8c, $1b, $95, $80, $1d, $89, $00, $89, $8e, $1f, $95, $80, $1d, $89, $00, $89, $8c, $1b, $95, $88
	.byte $1f, $95, $97, $80, $1d, $89, $00, $89, $8c, $1b, $95, $88, $1f, $ad, $80, $1d, $89, $00, $89, $8c, $1b, $95, $1b, $89
	.byte $1b
	.byte $41, $14
	.word @song0ref3037
	.byte $84, $1f, $89, $1f, $89, $1f, $89, $1f, $89, $1f, $89, $1f, $89, $86, $1b, $89, $1b, $89, $1b, $89, $1b, $89, $1a, $89
	.byte $1a, $89, $1a, $89, $1a
	.byte $41, $17
	.word @song0ref2544
	.byte $41, $0e
	.word @song0ref2548
	.byte $41, $16
	.word @song0ref2545
	.byte $86, $1c, $95, $82, $1f, $95, $88, $1f, $ad, $1f, $ad
	.byte $41, $16
	.word @song0ref2546
	.byte $41, $0e
	.word @song0ref2548
	.byte $41, $16
	.word @song0ref2545
	.byte $86, $1c, $95, $82, $1f, $95
	.byte $41, $10
	.word @song0ref2528
	.byte $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $af, $00, $ff, $8d, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $ff, $ff, $bf, $df, $52, $00
@song0ref3182:
	.byte $02, $89, $02, $89, $02, $89, $02, $89
@song0ref3190:
	.byte $02, $89, $02, $89, $02
@song0ref3195:
	.byte $89
@song0ref3196:
	.byte $02, $89
@song0ref3198:
	.byte $02, $89, $00
@song0ref3201:
	.byte $a1
@song0ref3202:
	.byte $02, $89, $00, $a1, $02, $89, $00, $a1, $02, $89, $00, $89, $03, $95
	.byte $41, $12
	.word @song0ref3198
	.byte $41, $12
	.word @song0ref3198
	.byte $41, $0f
	.word @song0ref3198
	.byte $41, $0c
	.word @song0ref3201
	.byte $a1, $02, $89, $00, $89, $03, $95
	.byte $41, $12
	.word @song0ref3198
	.byte $41, $12
	.word @song0ref3198
	.byte $02, $89, $00, $a1, $02, $89, $00, $a1
	.byte $41, $10
	.word @song0ref3182
@song0ch4loop:
@song0ref3253:
	.byte $02, $89, $00, $a1, $01, $95, $00, $ad, $02, $89, $00, $89, $01, $95, $00, $95
	.byte $41, $0d
	.word @song0ref3253
	.byte $89, $00, $89, $01, $89, $01, $89
@song0ref3279:
	.byte $02, $89, $00, $a1, $01, $89, $00, $b9, $02, $89, $00, $89, $01, $89, $00, $a1
	.byte $41, $0c
	.word @song0ref3279
	.byte $41, $1a
	.word @song0ref3190
	.byte $41, $12
	.word @song0ref3198
	.byte $41, $12
	.word @song0ref3198
	.byte $41, $0e
	.word @song0ref3198
	.byte $02, $89, $00
	.byte $41, $15
	.word @song0ref3195
	.byte $41, $12
	.word @song0ref3198
	.byte $41, $12
	.word @song0ref3198
	.byte $02, $89, $00, $95
@song0ref3326:
	.byte $02, $89, $00, $95, $02, $89, $00, $95, $02, $89, $00, $89, $02, $83, $02, $83, $02, $95, $02, $83, $02, $83
	.byte $41, $14
	.word @song0ref3196
	.byte $41, $12
	.word @song0ref3198
	.byte $41, $12
	.word @song0ref3198
	.byte $41, $0c
	.word @song0ref3202
@song0ref3360:
	.byte $02, $89, $00, $89, $02, $89, $02, $89, $02, $89, $02, $89, $02, $93, $00, $af, $02, $93, $00, $af
@song0ref3380:
	.byte $02, $89, $00, $89, $02
@song0ref3385:
	.byte $89, $00, $89, $97, $02, $89, $00, $a1, $02, $89, $00, $a1
	.byte $41, $0d
	.word @song0ref3326
	.byte $89, $00, $89, $02, $89, $00, $89, $02, $89, $00, $89
	.byte $41, $0d
	.word @song0ref3360
	.byte $41, $0c
	.word @song0ref3385
	.byte $41, $0d
	.word @song0ref3360
@song0ref3420:
	.byte $89, $00, $89, $01
@song0ref3424:
	.byte $95, $02, $89, $00, $89, $01, $95, $02, $89, $00, $89, $01, $95, $02, $89, $00, $89, $03
	.byte $41, $11
	.word @song0ref3424
	.byte $01, $95, $02, $89, $00, $89, $03
	.byte $41, $11
	.word @song0ref3424
	.byte $01, $95, $02, $89, $00, $89, $03
	.byte $41, $11
	.word @song0ref3424
	.byte $41, $0d
	.word @song0ref3360
	.byte $41, $16
	.word @song0ref3420
	.byte $41, $11
	.word @song0ref3424
	.byte $01, $95, $02, $89, $00, $89, $03
	.byte $41, $11
	.word @song0ref3424
	.byte $01, $95
	.byte $41, $0c
	.word @song0ref3380
	.byte $89, $02, $89, $00, $89, $02, $89, $00, $a1
	.byte $41, $0d
	.word @song0ref3360
@song0ref3501:
	.byte $89, $00, $89
@song0ref3504:
	.byte $02, $89, $00, $89, $01, $89, $00, $89, $02, $89, $00, $a1, $02, $89, $00, $89, $01, $89, $00, $89, $02, $89, $00, $89
	.byte $97
	.byte $41, $14
	.word @song0ref3504
	.byte $01, $89, $52, $00, $01, $89, $02
	.byte $41, $1b
	.word @song0ref3501
	.byte $df
	.byte $41, $22
	.word @song0ref3182
	.byte $41, $12
	.word @song0ref3198
	.byte $41, $12
	.word @song0ref3198
	.byte $41, $0f
	.word @song0ref3198
	.byte $41, $0c
	.word @song0ref3201
	.byte $a1, $02, $89, $00, $89, $03, $95
	.byte $41, $12
	.word @song0ref3198
	.byte $41, $12
	.word @song0ref3198
	.byte $02, $89, $00, $a1, $02, $89, $00, $a1
	.byte $41, $10
	.word @song0ref3182
	.byte $42
	.word @song0ch4loop
@song0ch5:
@song0ref3585:
	.byte $84, $2e, $89
@song0ref3588:
	.byte $33, $89, $38, $89, $3c, $89, $40, $4f
@song0ref3596:
	.byte $89, $2e, $89, $33, $89, $38, $89, $3c, $89, $40, $4f, $89, $2e, $89, $33, $89, $38, $89, $3c, $89, $40, $4f, $89, $3c
	.byte $41, $15
	.word @song0ref3596
@song0ref3623:
	.byte $2e, $89, $33, $89, $38, $89, $3c, $89, $40, $4f
@song0ref3633:
	.byte $89, $3c
@song0ref3635:
	.byte $89, $2e, $89, $35, $89, $38, $89, $3c, $89, $3e, $89, $2e, $89, $35, $89, $38, $89, $3c, $89, $3e, $89, $2e, $89, $35
	.byte $89, $38, $89, $3c, $89, $3e
	.byte $41, $20
	.word @song0ref3633
	.byte $89, $3a
	.byte $41, $15
	.word @song0ref3596
	.byte $41, $0e
	.word @song0ref3623
	.byte $41, $1d
	.word @song0ref3588
	.byte $41, $1e
	.word @song0ref3635
	.byte $89, $3c, $89
@song0ref3685:
	.byte $2e, $8d, $35, $8d, $38, $8d, $3c, $8d, $3e, $8d, $2e, $8d, $35, $8d, $38, $8d, $3c, $8d, $3e, $8d, $2e, $8d, $35, $8d
	.byte $38, $9d, $3c, $9d, $51, $fb, $10, $3e, $dd, $51, $05, $f0, $49, .lobyte(@env41), .hibyte(@env41), $80, $26, $dd, $df
	.byte $00, $dd, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80
@song0ref3735:
	.byte $27, $87, $5a, $27, $87, $5a, $00, $89, $27, $87, $5a, $00, $95, $27, $87, $5a, $00, $89, $27, $87, $5a, $27, $87, $5a
	.byte $00, $89, $27, $87, $5a, $27, $93, $5a, $27, $93, $5a, $24, $89, $43, $26, $87, $5a, $00, $89, $26, $87, $5a, $00, $95
	.byte $26, $87, $5a, $00, $89, $24, $89, $43, $26, $87, $5a, $00, $89, $26, $87, $5a, $26, $93, $5a, $78, $26, $87, $5a, $7f
	.byte $26, $87, $5a, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $41, $34
	.word @song0ref3735
	.byte $26, $95, $43, $50, $f8, $32, $26, $95, $25, $95, $43, $50, $f8, $31, $25, $95, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a
	.byte $41, $47
	.word @song0ref3735
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $41, $34
	.word @song0ref3735
	.byte $26, $95, $43, $50, $f8, $32, $26, $95, $25, $95, $43, $50, $f8, $31, $25, $95
@song0ch5loop:
	.byte $7f
@song0ref3865:
	.byte $24, $95, $5a, $95, $71, $24, $ad, $51, $0a, $f0, $af, $ad, $5a, $24, $95, $5a, $95, $71, $24, $ad, $51, $0a, $f0, $af
	.byte $ad, $5a
	.byte $41, $12
	.word @song0ref3865
@song0ref3894:
	.byte $27, $93, $5a, $76, $27, $87, $5a, $7f, $27, $93, $5a, $76, $27, $87, $5a, $7f, $27, $93, $5a, $76, $27, $93, $5a, $7f
	.byte $41, $0c
	.word @song0ref3894
@song0ref3921:
	.byte $7f, $26, $93, $5a, $76, $26, $87, $5a, $7f, $26, $93, $5a, $76, $26, $87, $5a, $7f, $26, $93, $5a, $76, $26, $93, $5a
	.byte $41, $0c
	.word @song0ref3921
	.byte $7f
	.byte $41, $12
	.word @song0ref3894
	.byte $7f
	.byte $41, $0c
	.word @song0ref3894
	.byte $41, $12
	.word @song0ref3921
	.byte $41, $0c
	.word @song0ref3921
	.byte $7f
	.byte $41, $12
	.word @song0ref3894
	.byte $7f
	.byte $41, $0c
	.word @song0ref3894
	.byte $41, $12
	.word @song0ref3921
	.byte $41, $0c
	.word @song0ref3921
	.byte $7f
	.byte $41, $12
	.word @song0ref3894
	.byte $7f
	.byte $41, $0c
	.word @song0ref3894
	.byte $7f, $00, $ff, $bd
	.byte $41, $12
	.word @song0ref3894
	.byte $7f
	.byte $41, $0c
	.word @song0ref3894
	.byte $41, $12
	.word @song0ref3921
	.byte $41, $0c
	.word @song0ref3921
	.byte $7f
	.byte $41, $12
	.word @song0ref3894
	.byte $7f
	.byte $41, $0c
	.word @song0ref3894
	.byte $41, $12
	.word @song0ref3921
	.byte $41, $0c
	.word @song0ref3921
	.byte $7f, $50, $08, $31, $35, $89, $43, $29, $89, $49, .lobyte(@env41), .hibyte(@env41), $ad, $5a, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $80, $50, $06, $30, $33, $89, $43, $27, $89, $49, .lobyte(@env41), .hibyte(@env41), $c5, $5a, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $80, $50, $05, $2e, $31, $89, $43, $25, $89, $49, .lobyte(@env41), .hibyte(@env41), $c5, $5a, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $80, $50, $06, $2c, $30, $89, $43, $24, $89, $49, .lobyte(@env41), .hibyte(@env41)
	.byte $c5, $5a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $50, $05, $2e, $31, $89, $43, $25, $89, $49, .lobyte(@env41)
	.byte .hibyte(@env41), $ff, $a5, $5a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $29, $93, $5a, $76, $29, $93, $5a, $7f
	.byte $29, $93, $5a, $76, $29, $93, $5a, $7f, $28, $95, $43, $50, $f7, $34, $28, $95, $00, $c5
@song0ref4133:
	.byte $2c, $93, $5a, $00, $89, $2b, $93, $5a, $00, $89, $2c, $93, $5a, $00, $89, $2c, $93, $5a, $00, $89, $2c, $87, $5a, $2c
	.byte $87, $5a, $2b, $93, $5a
	.byte $41, $1d
	.word @song0ref4133
	.byte $41, $1d
	.word @song0ref4133
	.byte $41, $1d
	.word @song0ref4133
	.byte $41, $1d
	.word @song0ref4133
	.byte $41, $1d
	.word @song0ref4133
	.byte $41, $1a
	.word @song0ref4133
	.byte $29, $93, $5a, $00, $95, $29, $93, $5a, $00, $95, $28, $93, $5a, $00, $93, $81, $74, $30, $87, $5a, $76, $30, $87, $5a
	.byte $78, $30, $87, $5a, $7a, $30, $87, $5a, $7b, $30, $87, $5a, $7d, $30, $87, $5a, $7f
@song0ref4221:
	.byte $20, $89, $22, $89, $25, $89, $29, $89, $20, $89, $22, $89, $25, $89, $29, $89, $30, $89, $29, $89, $25, $89, $22, $89
	.byte $20, $89, $1d, $89, $22, $89, $24, $89, $27, $89, $2b, $89, $27, $89, $24, $89, $22, $89, $24, $89, $20, $89, $24, $89
	.byte $27, $89, $29, $89, $27, $89, $24, $89, $20, $89, $24, $89, $27, $89, $29, $89, $25, $89, $29, $89, $2c, $89, $30, $89
	.byte $2c, $89, $27, $89, $2b, $89, $2e, $89, $33, $89, $2e, $89, $2b, $89, $27, $89, $2b, $89, $2e, $89, $27, $95, $8b, $43
	.byte $50, $ef, $33, $27, $89, $00, $c5, $71, $27, $95, $51, $13, $f0, $97, $ad, $5a, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a
	.byte $41, $47
	.word @song0ref3735
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $41, $34
	.word @song0ref3735
	.byte $26, $95, $43, $50, $f8, $32, $26, $95, $25, $95, $43, $50, $f8, $31, $25, $95, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a
	.byte $41, $47
	.word @song0ref3735
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $41, $34
	.word @song0ref3735
	.byte $26, $95, $43, $50, $f8, $32, $26, $95, $25, $95, $43, $50, $f8, $31, $25, $95, $42
	.word @song0ch5loop
@song0ch6:
	.byte $97, $76
	.byte $41, $1f
	.word @song0ref3585
	.byte $41, $15
	.word @song0ref3596
	.byte $41, $29
	.word @song0ref3623
	.byte $41, $20
	.word @song0ref3633
	.byte $89, $3a
	.byte $41, $15
	.word @song0ref3596
	.byte $41, $0e
	.word @song0ref3623
	.byte $41, $1d
	.word @song0ref3588
	.byte $41, $1e
	.word @song0ref3635
	.byte $87, $3c, $8b
	.byte $41, $1b
	.word @song0ref3685
	.byte $85, $97, $51, $fd, $10, $3e, $c5, $51, $05, $f0, $49, .lobyte(@env41), .hibyte(@env41), $80, $24, $dd, $df, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $00, $dd, $80
@song0ref4454:
	.byte $24, $87, $5a
@song0ref4457:
	.byte $24, $87, $5a, $00, $89, $24, $87, $5a, $00, $95, $24, $87, $5a, $00, $89, $24, $87, $5a, $24, $87, $5a, $00, $89, $24
	.byte $87, $5a, $24, $93, $5a, $24, $93, $5a, $22, $89, $43
	.byte $41, $0f
	.word @song0ref4457
@song0ref4495:
	.byte $22, $89, $43, $24, $87, $5a, $00, $89, $24, $87, $5a, $24, $93, $5a, $78, $24, $87, $5a, $7f, $24, $87, $5a
	.byte $41, $25
	.word @song0ref4454
	.byte $43
	.byte $41, $10
	.word @song0ref4457
	.byte $95, $43, $50, $f9, $30, $24, $95, $23, $95, $43, $50, $f9, $2f, $23, $95
	.byte $41, $25
	.word @song0ref4454
	.byte $43
	.byte $41, $0f
	.word @song0ref4457
	.byte $41, $13
	.word @song0ref4495
	.byte $41, $25
	.word @song0ref4454
	.byte $43
	.byte $41, $10
	.word @song0ref4457
	.byte $95, $43, $50, $f9, $30, $24, $95, $23, $95, $43, $50, $f9, $2f, $23, $95
@song0ch6loop:
	.byte $7f
@song0ref4573:
	.byte $22, $95, $5a, $95, $71, $22, $ad, $51, $0a, $f0, $af, $ad, $5a, $22, $95, $5a, $95, $71, $22, $ad, $51, $0a, $f0, $af
	.byte $ad, $5a
	.byte $41, $12
	.word @song0ref4573
@song0ref4602:
	.byte $24, $93, $5a, $76, $24, $87, $5a, $7f, $24, $93, $5a, $76, $24, $87, $5a, $7f, $24, $93, $5a, $76, $24, $93, $5a, $7f
	.byte $41, $0c
	.word @song0ref4602
@song0ref4629:
	.byte $7f, $22, $93, $5a, $76, $22, $87, $5a, $7f, $22, $93, $5a, $76, $22, $87, $5a, $7f, $22, $93, $5a, $76, $22, $93, $5a
	.byte $41, $0c
	.word @song0ref4629
	.byte $7f
	.byte $41, $12
	.word @song0ref4602
	.byte $7f
	.byte $41, $0c
	.word @song0ref4602
	.byte $41, $12
	.word @song0ref4629
	.byte $41, $0c
	.word @song0ref4629
	.byte $7f
	.byte $41, $12
	.word @song0ref4602
	.byte $7f
	.byte $41, $0c
	.word @song0ref4602
	.byte $41, $12
	.word @song0ref4629
	.byte $41, $0c
	.word @song0ref4629
	.byte $7f
	.byte $41, $12
	.word @song0ref4602
	.byte $7f
	.byte $41, $0c
	.word @song0ref4602
	.byte $7f, $00, $ff, $bd
	.byte $41, $12
	.word @song0ref4602
	.byte $7f
	.byte $41, $0c
	.word @song0ref4602
	.byte $41, $12
	.word @song0ref4629
	.byte $41, $0c
	.word @song0ref4629
	.byte $7f
	.byte $41, $12
	.word @song0ref4602
	.byte $7f
	.byte $41, $0c
	.word @song0ref4602
	.byte $41, $12
	.word @song0ref4629
	.byte $41, $0c
	.word @song0ref4629
	.byte $7f, $50, $08, $2c, $31, $89, $43, $25, $89, $49, .lobyte(@env41), .hibyte(@env41), $ad, $5a, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $80, $50, $08, $2b, $30, $89, $43, $24, $89, $49, .lobyte(@env41), .hibyte(@env41), $c5, $5a, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $80, $50, $07, $29, $2e, $89, $43, $22, $89, $49, .lobyte(@env41), .hibyte(@env41), $c5, $5a, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $80, $50, $06, $27, $2c, $89, $43, $20, $89, $49, .lobyte(@env41), .hibyte(@env41)
	.byte $c5, $5a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $50, $06, $2a, $2e, $89, $43, $22, $89, $49, .lobyte(@env41)
	.byte .hibyte(@env41), $ff, $a5, $5a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $24, $93, $5a, $76, $24, $93, $5a, $7f
	.byte $24, $93, $5a, $76, $24, $93, $5a, $7f, $24, $95, $43, $50, $f9, $30, $24, $95, $00, $c5
@song0ref4841:
	.byte $29, $93, $5a, $00, $89, $27, $93, $5a, $00, $89, $29, $93, $5a, $00, $89, $29, $93, $5a, $00, $89, $29, $87, $5a, $29
	.byte $87, $5a, $27, $93, $5a
	.byte $41, $1d
	.word @song0ref4841
	.byte $41, $1d
	.word @song0ref4841
	.byte $41, $1d
	.word @song0ref4841
	.byte $41, $1d
	.word @song0ref4841
	.byte $41, $1d
	.word @song0ref4841
	.byte $41, $1a
	.word @song0ref4841
	.byte $24, $93, $5a, $00, $95, $24, $93, $5a, $00, $95, $24, $93, $5a, $00, $93, $81, $74, $2b, $87, $5a, $76, $2b, $87, $5a
	.byte $78, $2b, $87, $5a, $7a, $2b, $87, $5a, $7b, $2b, $87, $5a, $2b, $87, $5a, $7f
@song0ref4928:
	.byte $1d, $89, $20, $89, $22, $89, $25, $89, $1d, $89, $20, $89, $24, $89, $25, $89, $2c, $89, $25, $89, $24, $89, $20, $89
	.byte $1d, $89, $19, $89, $1f, $89, $22, $89, $24, $89, $27, $89, $24, $89, $22, $89, $1f, $89, $22, $89, $1d, $89, $20, $89
	.byte $24, $89, $27, $89, $24, $89, $20, $89, $1d, $89, $20, $89, $24, $89, $27, $89, $20, $89, $25, $89, $29, $89, $2c, $89
	.byte $29, $89, $25, $89, $27, $89, $2b, $89, $2e, $89, $2b, $89, $27, $89, $22, $89, $27, $89, $2b, $89, $24, $95, $8b, $43
	.byte $50, $f2, $30, $24, $89, $00, $c5, $71, $24, $95, $51, $13, $f0, $97, $ad, $5a
	.byte $41, $25
	.word @song0ref4454
	.byte $43
	.byte $41, $0f
	.word @song0ref4457
	.byte $41, $13
	.word @song0ref4495
	.byte $41, $25
	.word @song0ref4454
	.byte $43
	.byte $41, $10
	.word @song0ref4457
	.byte $95, $43, $50, $f9, $30, $24, $95, $23, $95, $43, $50, $f9, $2f, $23, $95
	.byte $41, $25
	.word @song0ref4454
	.byte $43
	.byte $41, $0f
	.word @song0ref4457
	.byte $41, $13
	.word @song0ref4495
	.byte $41, $25
	.word @song0ref4454
	.byte $43
	.byte $41, $10
	.word @song0ref4457
	.byte $95, $43, $50, $f9, $30, $24, $95, $23, $95, $43, $50, $f9, $2f, $23, $95, $42
	.word @song0ch6loop
@song0ch7:
	.byte $41, $10
	.word @song0ref1203
	.byte $df, $71, $51, $05, $f0, $49, .lobyte(@env41), .hibyte(@env41), $80, $20, $dd, $df, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $00, $dd, $80
@song0ref5129:
	.byte $20, $87, $5a
@song0ref5132:
	.byte $20, $87, $5a, $00, $89, $20, $87, $5a, $00, $95, $20, $87, $5a, $00, $89, $20, $87, $5a, $20, $87, $5a, $00, $89, $20
	.byte $87, $5a, $20, $93, $5a, $20, $93, $5a, $1d, $89, $43
	.byte $41, $0f
	.word @song0ref5132
@song0ref5170:
	.byte $1d, $89, $43, $20, $87, $5a, $00, $89, $20, $87, $5a, $20, $93, $5a, $78, $20, $87, $5a, $7f, $20, $87, $5a
	.byte $41, $25
	.word @song0ref5129
	.byte $43
	.byte $41, $10
	.word @song0ref5132
	.byte $95, $43, $50, $fa, $2c, $20, $95, $20, $95, $43, $50, $fa, $2c, $20, $95
	.byte $41, $25
	.word @song0ref5129
	.byte $43
	.byte $41, $0f
	.word @song0ref5132
	.byte $41, $13
	.word @song0ref5170
	.byte $41, $25
	.word @song0ref5129
	.byte $43
	.byte $41, $10
	.word @song0ref5132
	.byte $95, $43, $50, $fa, $2c, $20, $95, $20, $95, $43, $50, $fa, $2c, $20, $95
@song0ch7loop:
	.byte $7f
@song0ref5248:
	.byte $27, $95, $5a, $95, $71, $27, $ad, $51, $0a, $f0, $af, $ad, $5a, $27, $95, $5a, $95, $71, $27, $ad, $51, $0a, $f0, $af
	.byte $ad, $5a
	.byte $41, $12
	.word @song0ref5248
@song0ref5277:
	.byte $20, $93, $5a, $76, $20
@song0ref5282:
	.byte $87, $5a, $7f, $20, $93, $5a, $76, $20, $87, $5a, $7f, $20, $93, $5a, $76, $20, $93, $5a, $7f
	.byte $41, $10
	.word @song0ref5277
	.byte $41, $0e
	.word @song0ref5282
	.byte $7f
	.byte $41, $10
	.word @song0ref5277
	.byte $41, $0e
	.word @song0ref5282
	.byte $7f
	.byte $41, $10
	.word @song0ref5277
	.byte $41, $0e
	.word @song0ref5282
	.byte $7f
	.byte $41, $10
	.word @song0ref5277
	.byte $41, $0e
	.word @song0ref5282
	.byte $7f
	.byte $41, $10
	.word @song0ref5277
	.byte $41, $0e
	.word @song0ref5282
	.byte $7f
	.byte $41, $10
	.word @song0ref5277
	.byte $41, $0e
	.word @song0ref5282
	.byte $7f
	.byte $41, $0c
	.word @song0ref5277
	.byte $7f, $00, $ff, $bd
	.byte $41, $12
	.word @song0ref5277
	.byte $7f
	.byte $41, $10
	.word @song0ref5277
	.byte $41, $0e
	.word @song0ref5282
	.byte $7f
	.byte $41, $10
	.word @song0ref5277
	.byte $41, $0e
	.word @song0ref5282
	.byte $7f
	.byte $41, $10
	.word @song0ref5277
	.byte $41, $0e
	.word @song0ref5282
	.byte $7f
	.byte $41, $0c
	.word @song0ref5277
	.byte $7f, $50, $04, $29, $2c, $89, $43, $20, $89, $49, .lobyte(@env41), .hibyte(@env41), $ad, $5a, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $80, $50, $05, $27, $2b, $89, $43, $1f, $89, $49, .lobyte(@env41), .hibyte(@env41), $c5, $5a, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $80, $50, $04, $25, $29, $89, $43, $1d, $89, $49, .lobyte(@env41), .hibyte(@env41), $c5, $5a, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $80, $50, $03, $24, $27, $89, $43, $1b, $89, $49, .lobyte(@env41), .hibyte(@env41)
	.byte $c5, $5a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $50, $06, $25, $2a, $89, $43, $1e, $89, $49, .lobyte(@env41)
	.byte .hibyte(@env41), $ff, $a5, $5a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $22, $93, $5a, $76, $22, $93, $5a, $7f
	.byte $22, $93, $5a, $76, $22, $93, $5a, $7f, $22, $95, $43, $50, $f9, $2e, $22, $95, $00, $c5
@song0ref5496:
	.byte $24, $93, $5a, $00, $89, $22, $93, $5a, $00, $89, $24, $93, $5a, $00, $89, $24, $93, $5a, $00, $89, $24, $87, $5a, $24
	.byte $87, $5a, $22, $93, $5a
	.byte $41, $1d
	.word @song0ref5496
	.byte $41, $1d
	.word @song0ref5496
	.byte $41, $1d
	.word @song0ref5496
	.byte $41, $1d
	.word @song0ref5496
	.byte $41, $1d
	.word @song0ref5496
	.byte $41, $1d
	.word @song0ref5496
	.byte $00, $95, $22, $93, $5a, $00, $95, $22, $93, $5a, $00, $93, $81, $74, $29, $87, $5a, $75, $29, $87, $5a, $77, $29, $87
	.byte $5a, $79, $29, $87, $5a, $7b, $29, $87, $5a, $7d, $29, $87, $5a, $74, $00, $95
	.byte $41, $58
	.word @song0ref4221
	.byte $7f, $22, $95, $8b, $43, $50, $f3, $2e, $22, $89, $00, $c5, $71, $22, $95, $51, $13, $f0, $97, $ad, $5a
	.byte $41, $25
	.word @song0ref5129
	.byte $43
	.byte $41, $0f
	.word @song0ref5132
	.byte $41, $13
	.word @song0ref5170
	.byte $41, $25
	.word @song0ref5129
	.byte $43
	.byte $41, $10
	.word @song0ref5132
	.byte $95, $43, $50, $fa, $2c, $20, $95, $20, $95, $43, $50, $fa, $2c, $20, $95
	.byte $41, $25
	.word @song0ref5129
	.byte $43
	.byte $41, $0f
	.word @song0ref5132
	.byte $41, $13
	.word @song0ref5170
	.byte $41, $25
	.word @song0ref5129
	.byte $43
	.byte $41, $10
	.word @song0ref5132
	.byte $95, $43, $50, $fa, $2c, $20, $95, $20, $95, $43, $50, $fa, $2c, $20, $95, $42
	.word @song0ch7loop
@song0ch8:
	.byte $41, $10
	.word @song0ref1203
	.byte $df, $71, $51, $05, $f0, $49, .lobyte(@env41), .hibyte(@env41), $80, $22, $dd, $df, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $00, $dd, $80
@song0ref5696:
	.byte $22, $87, $5a
@song0ref5699:
	.byte $22, $87, $5a, $00, $89, $22, $87, $5a, $00, $95, $22, $87, $5a, $00, $89, $22, $87, $5a, $22, $87, $5a, $00, $89, $22
	.byte $87, $5a, $22, $93, $5a, $22, $93, $5a, $20, $89, $43
	.byte $41, $0f
	.word @song0ref5699
@song0ref5737:
	.byte $20, $89, $43, $22, $87, $5a, $00, $89, $22, $87, $5a, $22, $93, $5a, $78, $22, $87, $5a, $7f, $22, $87, $5a
	.byte $41, $25
	.word @song0ref5696
	.byte $43
	.byte $41, $10
	.word @song0ref5699
	.byte $95, $43, $50, $f9, $2e, $22, $95, $21, $95, $43, $50, $fa, $2d, $21, $95
	.byte $41, $25
	.word @song0ref5696
	.byte $43
	.byte $41, $0f
	.word @song0ref5699
	.byte $41, $13
	.word @song0ref5737
	.byte $41, $25
	.word @song0ref5696
	.byte $43
	.byte $41, $10
	.word @song0ref5699
	.byte $95, $43, $50, $f9, $2e, $22, $95, $21, $95, $43, $50, $fa, $2d, $21, $95
@song0ch8loop:
	.byte $7f
@song0ref5815:
	.byte $20, $95, $5a, $95, $71, $20, $ad, $51, $0a, $f0, $af, $ad, $5a, $20, $95, $5a, $95, $71, $20, $ad, $51, $0a, $f0, $af
	.byte $ad, $5a
	.byte $41, $12
	.word @song0ref5815
@song0ref5844:
	.byte $1d, $93, $5a, $76, $1d
@song0ref5849:
	.byte $87, $5a, $7f, $1d, $93, $5a, $76, $1d, $87, $5a, $7f, $1d, $93, $5a, $76, $1d, $93, $5a, $7f
	.byte $41, $10
	.word @song0ref5844
	.byte $41, $0e
	.word @song0ref5849
	.byte $7f
	.byte $41, $10
	.word @song0ref5844
	.byte $41, $0e
	.word @song0ref5849
	.byte $7f
	.byte $41, $10
	.word @song0ref5844
	.byte $41, $0e
	.word @song0ref5849
	.byte $7f
	.byte $41, $10
	.word @song0ref5844
	.byte $41, $0e
	.word @song0ref5849
	.byte $7f
	.byte $41, $10
	.word @song0ref5844
	.byte $41, $0e
	.word @song0ref5849
	.byte $7f
	.byte $41, $10
	.word @song0ref5844
	.byte $41, $0e
	.word @song0ref5849
	.byte $7f
	.byte $41, $0c
	.word @song0ref5844
	.byte $7f, $00, $ff, $bd
	.byte $41, $12
	.word @song0ref5844
	.byte $7f
	.byte $41, $10
	.word @song0ref5844
	.byte $41, $0e
	.word @song0ref5849
	.byte $7f
	.byte $41, $10
	.word @song0ref5844
	.byte $41, $0e
	.word @song0ref5849
	.byte $7f
	.byte $41, $10
	.word @song0ref5844
	.byte $41, $0e
	.word @song0ref5849
	.byte $7f
	.byte $41, $0c
	.word @song0ref5844
	.byte $7f, $50, $04, $25, $29, $89, $43, $1d, $89, $49, .lobyte(@env41), .hibyte(@env41), $ad, $5a, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $80, $50, $03, $24, $27, $89, $43, $1b, $89, $49, .lobyte(@env41), .hibyte(@env41), $c5, $5a, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $80, $50, $03, $22, $25, $89, $43, $19, $89, $49, .lobyte(@env41), .hibyte(@env41), $c5, $5a, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $80, $50, $03, $20, $24, $89, $43, $18, $89, $49, .lobyte(@env41), .hibyte(@env41)
	.byte $c5, $5a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $50, $03, $22, $25, $89, $43, $19, $89, $49, .lobyte(@env41)
	.byte .hibyte(@env41), $ff, $a5, $5a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $1f, $93, $5a, $76, $1f, $93, $5a, $7f
	.byte $1f, $93, $5a, $76, $1f, $93, $5a, $7f, $1f, $95, $43, $50, $fa, $2b, $1f, $95, $00, $c5
@song0ref6063:
	.byte $1d, $93, $5a, $00, $89, $1d, $93, $5a, $00, $89, $1d, $93, $5a, $00, $89, $1d, $93, $5a, $00, $89, $1d, $87, $5a, $1d
	.byte $87, $5a, $1b, $93, $5a, $20, $93, $5a, $00, $89, $20, $93, $5a, $00, $89, $20, $93, $5a, $00, $89, $20, $93, $5a, $00
	.byte $89, $20, $87, $5a, $20, $87, $5a, $18, $93, $5a, $19, $93, $5a, $00, $89, $19, $93, $5a, $00, $89, $19, $93, $5a, $00
	.byte $89, $19, $93, $5a, $00, $89, $19, $87, $5a, $19, $87, $5a, $14, $93, $5a, $1b, $93, $5a, $00, $89, $1b, $93, $5a, $00
	.byte $89, $1b, $93, $5a, $00, $89, $1b, $93, $5a, $00, $89, $1b, $87, $5a, $1b, $87, $5a, $16, $93, $5a
	.byte $41, $54
	.word @song0ref6063
	.byte $1f, $93, $5a, $00, $95, $1f, $93, $5a, $00, $95, $1f, $93, $5a, $00, $93, $81, $73, $28, $87, $5a, $75, $28, $87, $5a
	.byte $77, $28, $87, $5a, $79, $28, $87, $5a, $7b, $28, $87, $5a, $7e, $28, $87, $5a, $74, $00, $95
	.byte $41, $58
	.word @song0ref4928
	.byte $7f, $20, $95, $8b, $43, $50, $f4, $2c, $20, $89, $00, $c5, $71, $20, $95, $51, $13, $f0, $97, $ad, $5a
	.byte $41, $25
	.word @song0ref5696
	.byte $43
	.byte $41, $0f
	.word @song0ref5699
	.byte $41, $13
	.word @song0ref5737
	.byte $41, $25
	.word @song0ref5696
	.byte $43
	.byte $41, $10
	.word @song0ref5699
	.byte $95, $43, $50, $f9, $2e, $22, $95, $21, $95, $43, $50, $fa, $2d, $21, $95
	.byte $41, $25
	.word @song0ref5696
	.byte $43
	.byte $41, $0f
	.word @song0ref5699
	.byte $41, $13
	.word @song0ref5737
	.byte $41, $25
	.word @song0ref5696
	.byte $43
	.byte $41, $10
	.word @song0ref5699
	.byte $95, $43, $50, $f9, $2e, $22, $95, $21, $95, $43, $50, $fa, $2d, $21, $95, $42
	.word @song0ch8loop
@song0ch9:
	.byte $41, $10
	.word @song0ref1203
	.byte $df, $71, $51, $05, $f0, $82, $05, $dd, $df, $02, $89, $0e, $89, $03, $89, $0f, $89, $04, $89, $10, $89, $05, $89, $11
	.byte $89
@song0ref6344:
	.byte $0f, $93, $5a, $11, $93, $5a, $00, $95, $0c, $93, $5a, $0f, $93, $5a, $00, $89, $11, $87, $5a, $00, $89, $11, $87, $5a
	.byte $0c, $87, $5a, $0d, $87, $5a, $0e, $93, $5a, $0c, $93, $5a, $0e, $93, $5a, $05
@song0ref6384:
	.byte $95, $49, .lobyte(@env41), .hibyte(@env41), $95, $5a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $82, $11, $93, $5a
	.byte $0c, $93, $5a, $0e, $93, $5a
	.byte $41, $25
	.word @song0ref6344
@song0ref6407:
	.byte $87, $5a, $00, $89, $08, $85, $43, $0a, $8b, $5a, $05, $95, $43, $50, $fe, $11, $05, $95, $04, $95, $43, $50, $fe, $10
	.byte $04, $95
	.byte $41, $34
	.word @song0ref6344
	.byte $41, $25
	.word @song0ref6344
	.byte $41, $11
	.word @song0ref6407
@song0ch9loop:
@song0ref6443:
	.byte $05, $9f, $5a, $78, $05, $87, $5a, $7f, $11, $93, $5a, $0a, $87, $5a, $0c, $87, $5a, $05, $9f, $5a, $78, $05, $87, $5a
	.byte $7f, $11, $93, $5a, $05, $93, $5a, $05, $9f, $5a, $78, $05, $87, $5a, $7f, $11, $93, $5a, $78, $11, $93, $5a, $7f, $0f
	.byte $89, $43, $11, $87, $5a, $0f, $93, $5a, $08, $93, $5a, $07, $93, $5a, $05, $9f, $5a, $78, $05, $87, $5a, $7f, $11, $93
	.byte $5a, $08, $87, $5a, $0a, $87, $5a
	.byte $41, $18
	.word @song0ref6443
	.byte $0f, $87, $5a, $0c, $87, $5a, $00, $89, $0f, $87, $5a, $10, $87, $5a, $00, $89, $11, $95, $43, $50, $fe, $1d, $15, $95
	.byte $41, $27
	.word @song0ref6344
	.byte $0a
	.byte $41, $0c
	.word @song0ref6384
	.byte $41, $27
	.word @song0ref6344
@song0ref6559:
	.byte $16, $95, $49, .lobyte(@env41), .hibyte(@env41), $95, $5a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $82, $14, $93
	.byte $5a, $13, $87, $5a, $8b, $0c, $87, $5a, $0e, $87, $5a
	.byte $41, $27
	.word @song0ref6344
	.byte $41, $11
	.word @song0ref6559
	.byte $41, $0e
	.word @song0ref6344
	.byte $11, $87, $5a, $16, $87, $5a, $8b, $14, $87, $5a, $11, $87, $5a, $0f, $87, $5a, $86, $05, $93, $5a, $11, $87, $5a, $08
	.byte $93, $5a, $11, $87, $5a, $0a, $93, $5a, $11, $87, $5a, $0c, $87, $5a, $49, .lobyte(@env15), .hibyte(@env15), $17, $93
	.byte $5a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $86
@song0ref6642:
	.byte $16, $87, $5a, $14, $87, $5a, $11, $87, $5a, $0f, $87, $5a, $82
	.byte $41, $27
	.word @song0ref6344
	.byte $0a
	.byte $41, $0c
	.word @song0ref6384
	.byte $41, $27
	.word @song0ref6344
	.byte $41, $11
	.word @song0ref6559
	.byte $0d, $93, $5a, $08, $93, $5a, $0d, $93, $5a, $0c, $95, $5a, $95, $08, $93, $5a, $05, $93, $5a, $0a, $95, $95, $5a, $0c
	.byte $93, $5a, $0d, $93, $5a, $08, $ab, $5a, $14, $93, $5a, $0f, $93, $5a, $08, $93, $5a, $06, $93, $5a, $0a, $93, $5a, $0d
	.byte $93, $5a, $12, $ab, $5a, $0d, $93, $5a, $0a, $93, $5a, $0c, $95, $89, $5a, $78, $0c, $87, $5a, $7f, $0c, $9f, $5a, $78
	.byte $0c, $87, $5a, $7f, $0c, $9f, $5a, $78, $0c, $87, $5a, $7f, $86, $18, $93, $5a
	.byte $41, $0c
	.word @song0ref6642
	.byte $82
@song0ref6760:
	.byte $05, $93, $5a, $11, $93, $5a, $05, $93, $5a, $11, $93, $5a
	.byte $41, $0c
	.word @song0ref6760
@song0ref6775:
	.byte $08, $93, $5a, $14, $93, $5a, $08, $93, $5a, $14, $93, $5a
	.byte $41, $0c
	.word @song0ref6775
@song0ref6790:
	.byte $01, $93, $5a, $0d, $93, $5a, $01, $93, $5a, $0d, $93, $5a
	.byte $41, $0c
	.word @song0ref6790
	.byte $03, $93, $5a, $0f, $93, $5a, $03, $93, $5a, $0f, $93, $5a, $03, $93, $5a, $18, $93, $5a
	.byte $41, $0c
	.word @song0ref6642
	.byte $41, $0c
	.word @song0ref6760
	.byte $41, $0c
	.word @song0ref6760
	.byte $41, $0c
	.word @song0ref6775
	.byte $41, $0c
	.word @song0ref6775
	.byte $41, $0c
	.word @song0ref6790
	.byte $01, $93, $5a, $0d, $93, $5a, $01, $93, $5a, $0a, $95, $95, $5a, $0c, $93, $5a, $0d, $87, $5a, $00, $89, $0a, $85, $43
	.byte $0c, $97, $5a, $00, $89, $16, $93, $5a, $13, $87, $5a, $10, $87, $5a, $0c, $87, $5a, $0f, $87, $5a, $0a, $93, $5a, $01
	.byte $93, $5a, $05, $93, $5a, $0d, $ab, $5a, $05, $93, $5a, $0d, $93, $5a, $0c, $95, $93, $5a, $13, $95, $5a, $0f, $93, $5a
	.byte $11, $ab, $5a, $05, $93, $5a, $0c, $93, $5a, $0f, $93, $5a, $0d, $93, $5a, $08, $93, $5a, $0d, $93, $5a, $0f, $ab, $5a
	.byte $13, $93, $5a, $0f, $93, $5a, $05, $95, $8b, $43, $50, $fd, $11, $05, $89, $00, $c5, $71, $05, $95, $51, $13, $f0, $97
	.byte $ad, $5a
	.byte $41, $34
	.word @song0ref6344
	.byte $41, $25
	.word @song0ref6344
	.byte $41, $11
	.word @song0ref6407
	.byte $41, $34
	.word @song0ref6344
	.byte $41, $25
	.word @song0ref6344
	.byte $41, $11
	.word @song0ref6407
	.byte $42
	.word @song0ch9loop
